import random


CPT_CODE_SEED_DATA = [
    {
        "code": "97110",
        "definition": "Therapeutic Exercise",
        "short_definition": "TE",
        "use_modifier": "97164, 97168",
        "do_not_bill_with": None,
        "wc_fee_schedule": 43.04,
        "auto_usual_and_customary": 58.20,
        "current_medicare_fs": 29.10,
        "ma_wc_fee_schedule": 23.10,
        "x1_for_eval_code": None,
    },
    {
        "code": "97112",
        "definition": "Neuromuscular Reeducation",
        "short_definition": "NMR",
        "use_modifier": None,
        "do_not_bill_with": None,
        "wc_fee_schedule": 48.17,
        "auto_usual_and_customary": 64.50,
        "current_medicare_fs": 31.25,
        "ma_wc_fee_schedule": 24.80,
        "x1_for_eval_code": None,
    },
    {
        "code": "97116",
        "definition": "Gait Training",
        "short_definition": "GT",
        "use_modifier": None,
        "do_not_bill_with": None,
        "wc_fee_schedule": 39.75,
        "auto_usual_and_customary": 54.00,
        "current_medicare_fs": 27.90,
        "ma_wc_fee_schedule": 22.40,
        "x1_for_eval_code": None,
    },
    {
        "code": "97140",
        "definition": "Manual Therapy",
        "short_definition": "MT",
        "use_modifier": None,
        "do_not_bill_with": None,
        "wc_fee_schedule": 42.60,
        "auto_usual_and_customary": 59.25,
        "current_medicare_fs": 28.75,
        "ma_wc_fee_schedule": 23.00,
        "x1_for_eval_code": None,
    },
    {
        "code": "97530",
        "definition": "Therapeutic Activities",
        "short_definition": "TA",
        "use_modifier": None,
        "do_not_bill_with": None,
        "wc_fee_schedule": 46.85,
        "auto_usual_and_customary": 62.10,
        "current_medicare_fs": 30.50,
        "ma_wc_fee_schedule": 24.25,
        "x1_for_eval_code": None,
    },
    {
        "code": "97010",
        "definition": "Hot or Cold Packs",
        "short_definition": "HP/CP",
        "use_modifier": None,
        "do_not_bill_with": None,
        "wc_fee_schedule": 12.00,
        "auto_usual_and_customary": 18.00,
        "current_medicare_fs": 0.00,
        "ma_wc_fee_schedule": 8.00,
        "x1_for_eval_code": None,
    },
    {
        "code": "97014",
        "definition": "Electrical Stimulation",
        "short_definition": "ES",
        "use_modifier": None,
        "do_not_bill_with": None,
        "wc_fee_schedule": 18.50,
        "auto_usual_and_customary": 28.00,
        "current_medicare_fs": 0.00,
        "ma_wc_fee_schedule": 12.50,
        "x1_for_eval_code": None,
    },
    {
        "code": "97035",
        "definition": "Ultrasound Therapy",
        "short_definition": "US",
        "use_modifier": None,
        "do_not_bill_with": None,
        "wc_fee_schedule": 20.25,
        "auto_usual_and_customary": 32.00,
        "current_medicare_fs": 13.75,
        "ma_wc_fee_schedule": 11.20,
        "x1_for_eval_code": None,
    },
    {
        "code": "97161",
        "definition": "Physical Therapy Evaluation, Low Complexity",
        "short_definition": "PT Eval Low",
        "use_modifier": None,
        "do_not_bill_with": None,
        "wc_fee_schedule": 75.00,
        "auto_usual_and_customary": 120.00,
        "current_medicare_fs": 95.00,
        "ma_wc_fee_schedule": 70.00,
        "x1_for_eval_code": 1,
    },
    {
        "code": "97162",
        "definition": "Physical Therapy Evaluation, Moderate Complexity",
        "short_definition": "PT Eval Mod",
        "use_modifier": None,
        "do_not_bill_with": None,
        "wc_fee_schedule": 85.00,
        "auto_usual_and_customary": 140.00,
        "current_medicare_fs": 105.00,
        "ma_wc_fee_schedule": 80.00,
        "x1_for_eval_code": 1,
    },
    {
        "code": "97163",
        "definition": "Physical Therapy Evaluation, High Complexity",
        "short_definition": "PT Eval High",
        "use_modifier": None,
        "do_not_bill_with": None,
        "wc_fee_schedule": 95.00,
        "auto_usual_and_customary": 160.00,
        "current_medicare_fs": 115.00,
        "ma_wc_fee_schedule": 90.00,
        "x1_for_eval_code": 1,
    },
    {
        "code": "97164",
        "definition": "Physical Therapy Re-evaluation",
        "short_definition": "PT Re-eval",
        "use_modifier": None,
        "do_not_bill_with": None,
        "wc_fee_schedule": 65.00,
        "auto_usual_and_customary": 100.00,
        "current_medicare_fs": 75.00,
        "ma_wc_fee_schedule": 60.00,
        "x1_for_eval_code": 1,
    },
]


def generate_cpt_code_records() -> list[dict]:
    records = []

    for item in CPT_CODE_SEED_DATA:
        code = item["code"]

        records.append({
            "object": "CPT_Codes__c",
            "synthetic_id": code,
            "fields": {
                "Name": code,
                "CPT_CODE_ID__c": code,
                "Definition__c": item["definition"],
                "Short_Definition__c": item["short_definition"],
                "Use_Modifier__c": item["use_modifier"],
                "Do_Not_Bill_With__c": item["do_not_bill_with"],
                "WC_Fee_Schedule__c": item["wc_fee_schedule"],
                "Auto_Usual_and_Customary__c": item["auto_usual_and_customary"],
                "Current_Medicare_FS__c": item["current_medicare_fs"],
                "MA_WC_Fee_Schedule__c": item["ma_wc_fee_schedule"],
                "X1_for_eval_code__c": item["x1_for_eval_code"],
                "Notes__c": random.choice([
                    None,
                    "Synthetic CPT reference data for sandbox testing.",
                    "Generated for line item CPT lookup testing.",
                ]),
            },
            "meta": {
                "cpt_code": code,
            },
        })

    return records