SEED = 42

ACCOUNT_COUNT = 10
MIN_CONTACTS_PER_ACCOUNT = 1
MAX_CONTACTS_PER_ACCOUNT = 3

OUTPUT_DIR = "data"

EXPORT_RAW_DATA = True
LOAD_TO_SALESFORCE = True

SYNTHETIC_ID_FIELD = "Synthetic_Id__c"

PARENT_ACCOUNT_COUNT = 10
MIN_CHILD_ACCOUNTS_PER_PARENT = 0
MAX_CHILD_ACCOUNTS_PER_PARENT = 4

MIN_PARENT_CONTACTS_PER_ACCOUNT = 2
MAX_PARENT_CONTACTS_PER_ACCOUNT = 5

MIN_CHILD_CONTACTS_PER_ACCOUNT = 0
MAX_CHILD_CONTACTS_PER_ACCOUNT = 3

ARN_PAYOR_MASTER_COUNT = 25

ARN_PAYORS_PER_MASTER_MIN = 1
ARN_PAYORS_PER_MASTER_MAX = 3

PAYOR_ACCOUNT_COUNT = 25

PAYOR_ACCOUNT_RECORD_TYPE_DEVELOPER_NAME = "PayorBillReview"

MIN_PAYOR_CONTACTS_PER_ACCOUNT = 1
MAX_PAYOR_CONTACTS_PER_ACCOUNT = 4

DEPOSIT_COUNT = 12
DEPOSIT_RECORD_TYPE_DEVELOPER_NAME = None

MIN_INCOMING_CHECK_PAYMENTS_PER_BOOST = 0
MAX_INCOMING_CHECK_PAYMENTS_PER_BOOST = 2
INCOMING_CHECK_PAYMENT_PROBABILITY = 0.35

BOOST_TICKET_PROBABILITY = 0.35

MIN_BOOST_TICKETS_PER_SELECTED_BOOST = 1
MAX_BOOST_TICKETS_PER_SELECTED_BOOST = 1

CASE_PROBABILITY_PER_BOOST_TICKET = 0.75
MIN_CASES_PER_SELECTED_BOOST_TICKET = 1
MAX_CASES_PER_SELECTED_BOOST_TICKET = 3

CASE_RECORD_TYPE_DEVELOPER_NAME = None